<?php

return [
    'political_parties' => [
        'ACT Wazalendo',
        'ACT',
        'CHADEMA',
        'CCM',
        'CUF',
        'NCCR-Mageuzi',
        'UDP',
        'TLP',
        'CHAUSTA',
    ],

    'political_figures' => [
        'Zitto Kabwe',
        'Freeman Mbowe',
        'John Magufuli',
        'Samia Suluhu Hassan',
        'Tundu Lissu',
        'Bernard Membe',
        'Edward Lowassa',
        'Maalim Seif Sharif Hamad',
        'Joseph Butiku',
        'Philip Mpango',
        'Hussein Mwinyi',
        'January Makamba',
        'Hamisi Kigwangalla',
        'Nape Nnauye',
        'Halima Mdee',
    ],

    'government_terms' => [
        'Uchaguzi',
        'Kura',
        'Siasa',
        'Bunge',
        'Waziri Mkuu',
        'Rais',
        'mwanasiasa',
        'samia',
        'Samia',
        'Wanasiasa',
        'vyama',
        'Vyama',
        'chama',
        'Chama',
        'kiongozi',
        'Kiongozi',
        'Viongozi',
        'upinzani',
        'mbuge',
        'Mbunge',
        'wabunge',
        'Wabunge',
        'waziri',
        'Waziri',
        'Serikali',
        'Katiba',
        'Tume ya Taifa ya Uchaguzi',
        'Mjadala',
        'Tume ya Maadili',
        'Tume',
        'Uchaguzi Mkuu',
        'Uchaguzi',
        'Wananchi',
        'Viongozi wa Serikali',
        'Mabadiliko ya Katiba',
        'Mpango wa Maendeleo',
        'Demokrasia',
        'Mikutano ya Hadhara',
        'Kampeni za Kisiasa',
        'Wagombea',
        'Azimio la Arusha',
        'Majimbo',
        'Haki za Binadamu',
    ],

    'electoral_terms' => [
        'Tume ya Uchaguzi',
        'Taratibu za Uchaguzi',
        'Sheria za Uchaguzi',
        'Mapinduzi',
        'Vyombo vya Habari vya Siasa',
        'Uwazi wa Serikali',
        'Rasimu ya Katiba',
        'Msimamizi wa Uchaguzi',
        'Uhuru wa Kujieleza',
        'Wanachama',
    ],

    'international_terms' => [
        'EAC',
        'AU',
        'SADC',
        'Diplomasia',
        'Mkutano wa Wakuu wa Nchi',
        'Siasa za Afrika Mashariki',
    ],
];
